function loglogplot();
x = linspace(0,1,101);
y = sin(pi*x);
ys = [];
xs=[];
list = splitbezier2(x, y, 0, 0, 102);
ys = [ys, sum(list)/length(list)];
xs = [xs, length(list)];
list = splitbezier2(x, y, 0, 0, 52);
ys = [ys, sum(list)/length(list)];
xs = [xs, length(list)];
list = splitbezier2(x, y, 0, 0, 27);
ys = [ys, sum(list)/length(list)];
xs = [xs, length(list)];
list = splitbezier2(x, y, 0, 0, 15);
ys = [ys, sum(list)/length(list)];
xs = [xs, length(list)];
list = splitbezier2(x, y, 0, 0, 9);
ys = [ys, sum(list)/length(list)];
xs = [xs, length(list)];
list = splitbezier2(x, y, 0, 0, 6);
ys = [ys, sum(list)/length(list)];
xs = [xs, length(list)];
disp(xs);
disp(ys);
hold off;
loglog(xs, ys);
end